import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google";
import mindmap from "../img/mindmap.svg";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const raleway_heavy = Raleway({subsets: ["latin"], weight: "700"});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className="antialiased overflow-hidden h-[100vh] flex flex-col"
    >
        <div className="flex w-100 z-[999] p-5 text-5xl text-center flex-shrink py-6">
            <h1 className={raleway_heavy.className + " top-[20px] absolute left-[50%] translate-x-[-50%]"}>
                logo
            </h1>
        </div>
        {children}
    </body>
    </html>
  );
}
